---
title: "index"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---


### These are the most common words that popped into your heads {data-commentary-width=0}

```{r}
#data=read.csv(input, header=T,sep=";")
library(wordcloud)
sumv<-read.table("/home/webadmin/R/dtm-test/data/cwsum", header=T,sep="")
commonality.cloud(sumv,comonality.measure=min,scale=c(4,0.05),random.order=F, colors = brewer.pal(6, "PuBuGn"))
```

*** 



### Here you can see a wordcloud that represents the most frequent words based on gender {data-commentary-width=0}

```{r}
gsum2<-read.table("/home/webadmin/R/dtm-test/data/gsum", header=T,sep="")
gsum2<-as.matrix(gsum2)
colnames(gsum2)<-NULL
comparison.cloud(gsum2,scale=c(4,.5),max.words=300,colors=c("deepskyblue3","firebrick2","darkorchid3"))

```

***

### You can see a cluster dendrogram here {data-commentary-width=0}

```{r}
library(cluster)
traindtm<-read.table("/home/webadmin/R/dtm-test/data/dtm", header=T,sep="")
d<-dist(traindtm)
groups <- hclust(d,method="ward.D")
plot(groups, hang=-1)
rect.hclust(groups,3)
```

*** 



### This is a graphical representation of your clusters {data-commentary-width=0}

```{r}
kfit <- kmeans(d, 3, nstart=100)
clusplot(traindtm, kfit$cluster, color=T, shade=T, labels=3, lines=0)
```

*** 

